# -*- coding: utf-8 -*-
"""
Created on Tue May 19 19:12:25 2026

@author: dptro
"""

"""
parse_reflection_sweep.py
Parser for Reflection_sweep CSV files generated by the plasma/RF measurement system.

Usage:
    python parse_reflection_sweep.py <csv_file>
    python parse_reflection_sweep.py Reflection_sweep_d701831e_20260519_164611.csv
"""

import sys
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import os
# ── Column definitions ──────────────────────────────────────────────────────
NUMERIC_COLS = [
    "pressure", "Measured Pressure",
    "power", "frequency",
    "Temperaure3",                         # note: typo is in the source data
    "forward_power", "forward_power_error",
    "reverse_power", "reverse_power_error",
    "delivered_power", "delivered_power_error",
    "gamma", "gamma_error",
]

OPTIONAL_NUMERIC_COLS = [
    "Argon_Gas_Flow",   # may contain '?' when sensor is inactive
    "Nitrogen_Gas_Flow",
]


def load(filepath: str) -> pd.DataFrame:
    """Load a reflection-sweep CSV and return a cleaned DataFrame."""
    df = pd.read_csv(filepath)

    # Parse timestamps
    df["timestamp"] = pd.to_datetime(df["timestamp"], errors="coerce")
    df["date"] = pd.to_datetime(df["date"], errors="coerce").dt.date

    # Coerce optional columns: '?' → NaN, then numeric
    for col in OPTIONAL_NUMERIC_COLS:
        if col in df.columns:
            df[col] = pd.to_numeric(df[col].replace("?", np.nan), errors="coerce")

    # Ensure core numeric columns are the right dtype
    for col in NUMERIC_COLS:
        if col in df.columns:
            df[col] = pd.to_numeric(df[col], errors="coerce")

    return df


def summary(df: pd.DataFrame) -> None:
    """Print a concise summary of the dataset."""
    print("=" * 60)
    print("REFLECTION SWEEP — DATASET SUMMARY")
    print("=" * 60)
    print(f"  Rows          : {len(df)}")
    print(f"  Columns       : {len(df.columns)}")
    print(f"  Run ID(s)     : {', '.join(df['run_id'].unique())}")
    print(f"  Date(s)       : {', '.join(str(d) for d in df['date'].unique())}")
    print(f"  Time range    : {df['timestamp'].min()}  →  {df['timestamp'].max()}")
    print(f"  Frequency     : {df['frequency'].min()} – {df['frequency'].max()} MHz")
    print(f"  Set power     : {df['power'].unique()} W")
    print(f"  Pressure      : {df['pressure'].unique()} mTorr (set)  |  "
          f"{df['Measured Pressure'].min():.3f} – {df['Measured Pressure'].max():.3f} mTorr (measured)")
    print(f"  gamma range   : {df['gamma'].min():.4f} – {df['gamma'].max():.4f}")
    print()


def filter_by_frequency(df: pd.DataFrame, freq_min: float, freq_max: float) -> pd.DataFrame:
    """Return rows where frequency is within [freq_min, freq_max] MHz."""
    return df[(df["frequency"] >= freq_min) & (df["frequency"] <= freq_max)].copy()


def filter_by_gamma(df: pd.DataFrame, gamma_min: float = 0.0, gamma_max: float = 1.0) -> pd.DataFrame:
    """Return rows where gamma is within [gamma_min, gamma_max]."""
    return df[(df["gamma"] >= gamma_min) & (df["gamma"] <= gamma_max)].copy()


def get_minimum_reflection(df: pd.DataFrame) -> pd.Series:
    """Return the row with the lowest gamma (best impedance match)."""
    return df.loc[df["gamma"].idxmin()]


def stats_by_frequency(df: pd.DataFrame) -> pd.DataFrame:
    """Return mean ± std of key power/gamma columns, grouped by frequency."""
    cols = ["forward_power", "reverse_power", "delivered_power", "gamma"]
    return df.groupby("frequency")[cols].agg(["mean", "std"]).round(4)


def export(df: pd.DataFrame, out_path: str) -> None:
    """Save a DataFrame to CSV."""
    df.to_csv(out_path, index=False)
    print(f"Saved → {out_path}")



filename = r"C:\Users\dptro\Downloads\Reflection_sweep_524912d2_20260520_121715.csv"
df = load(filename)
df['NitrogenPercentMeasured'] = (df['Nitrogen_Gas_Flow'] / 
                         (df['Argon_Gas_Flow'] + df['Nitrogen_Gas_Flow']))
df['NitrogenPercentMeasured'] = df['NitrogenPercentMeasured'].round(3)  # or round(2)
idx = df.groupby(['Nitrogen_Percent','power'])['gamma'].idxmin()
df_optimum = df.loc[idx].copy()
df_optimum = df_optimum.rename(columns={
    "frequency": "optimum_frequency",
    "gamma": "optimum_gamma"
})

df_optimum = df_optimum[["power", "Nitrogen_Percent", "optimum_frequency", "optimum_gamma"]]
df = df.merge(df_optimum, on=["power", "Nitrogen_Percent"], how="left")
    
PlotData = df[["power", 'Nitrogen_Percent', "frequency", "gamma", "optimum_frequency", "optimum_gamma"]]


# # first deduplicate down to one row per (power, nitrogen_percent)
# grid_df = PlotData.drop_duplicates(subset=["power", 'NitrogenPercent'])

# x = np.sort(grid_df['NitrogenPercent'].unique())  # columns
# y = np.sort(grid_df["power"].unique())              # rows

# Build grid_df correctly from df_optimum directly — it's already one row per group
grid_df = df_optimum.copy()
grid_df = df_optimum  # one row per group, correct optimum values


x = np.sort(grid_df['Nitrogen_Percent'].unique())
y = np.sort(grid_df['power'].unique())
Z = grid_df.pivot(index="power", columns='Nitrogen_Percent', values="optimum_frequency")
Z2 = grid_df.pivot(index="power", columns='Nitrogen_Percent', values="optimum_gamma")

for j in df['Nitrogen_Percent'].unique():
    fixed_nitrogen = j

    plt.figure()
    for power, group in df[df['Nitrogen_Percent'] == fixed_nitrogen].groupby('power'):
        plt.errorbar(group['frequency'], group['gamma'], yerr=group['gamma_error'],
                     label=f"{power} W", capsize=3)

    plt.xlabel("Frequency (MHz)")
    plt.ylabel("Gamma (reflection coefficient)")
    plt.title(f"Reflection vs Frequency — Nitrogen {fixed_nitrogen}%")
    plt.legend(title="Power")
    plt.legend(loc = 'lower right')
    plt.show()

for j in df['power'].unique():
    fixed_power = j

    plt.figure()
    for nitrogen, group in df[df['power'] == fixed_power].groupby('Nitrogen_Percent'):
        plt.errorbar(group['frequency'], group['gamma'], yerr=group['gamma_error'],
                     label=f"{nitrogen:.1f}%", capsize=3)

    plt.xlabel("Frequency (MHz)")
    plt.ylabel("Gamma (reflection coefficient)")
    plt.title(f"Reflection vs Frequency — Power {j}W")
    plt.legend(title="Nitrogen %")
    plt.legend(loc = 'lower left')
    plt.show()


fig, ax = plt.subplots()
contour = ax.contourf(x, y, Z, cmap="viridis")
plt.colorbar(contour, ax=ax, label="Optimum Frequency (MHz)")
ax.set_xlabel("Nitrogen Percent / %")
ax.set_ylabel("Power (W)")
ax.set_title("Optimum Frequency / MHz")
plt.show()


fig, ax = plt.subplots()
contour = ax.contourf(x, y, Z2, cmap="viridis")
plt.colorbar(contour, ax=ax, label="Optimum Gamma ")
ax.set_xlabel("Nitrogen Percent / %")
ax.set_ylabel("Power (W)")
ax.set_title("Optimum Gamma / a.u.")
plt.show()




# Overview
summary(df)


base, ext = os.path.splitext(filename)
NewFilename = base + "_processed_1" + ext
df.to_csv(NewFilename, index=False)
